spring.application.name=consolerpggame

spring.datasource.url=jdbc:h2:mem:rpgdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.active-directory.profile.tenant-id=${AZURE_TENANT_ID}


